package com.example.ember.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * Ember — Material 3 color tokens.
 * Generated from the Ember design system (coral-seeded). Every on-/container
 * pairing meets WCAG AA. Raw role values; schemes are assembled in Theme.kt.
 */

// ---- Light ----
val md_primary_light = Color(0xFFBB3E1C)
val md_onPrimary_light = Color(0xFFFFFFFF)
val md_primaryContainer_light = Color(0xFFFFDBCF)
val md_onPrimaryContainer_light = Color(0xFF3A0B00)
val md_secondary_light = Color(0xFF77574E)
val md_onSecondary_light = Color(0xFFFFFFFF)
val md_secondaryContainer_light = Color(0xFFFFDBCF)
val md_onSecondaryContainer_light = Color(0xFF2C150D)
val md_tertiary_light = Color(0xFF6C5D2F)
val md_onTertiary_light = Color(0xFFFFFFFF)
val md_tertiaryContainer_light = Color(0xFFF6E1A6)
val md_onTertiaryContainer_light = Color(0xFF221B00)
val md_error_light = Color(0xFFBA1A1A)
val md_onError_light = Color(0xFFFFFFFF)
val md_errorContainer_light = Color(0xFFFFDAD6)
val md_onErrorContainer_light = Color(0xFF410002)
val md_background_light = Color(0xFFFFF8F6)
val md_onBackground_light = Color(0xFF231915)
val md_surface_light = Color(0xFFFFF8F6)
val md_onSurface_light = Color(0xFF231915)
val md_surfaceVariant_light = Color(0xFFF5DED6)
val md_onSurfaceVariant_light = Color(0xFF53433E)
val md_outline_light = Color(0xFF85736C)
val md_outlineVariant_light = Color(0xFFD8C2BA)
val md_inverseSurface_light = Color(0xFF3A2F2B)
val md_inverseOnSurface_light = Color(0xFFFFEDE7)
val md_inversePrimary_light = Color(0xFFFFB59E)
val md_scrim_light = Color(0xFF000000)
val md_surfaceDim_light = Color(0xFFE7D7CF)
val md_surfaceBright_light = Color(0xFFFFF8F6)
val md_surfaceContainerLowest_light = Color(0xFFFFFFFF)
val md_surfaceContainerLow_light = Color(0xFFFFF1EC)
val md_surfaceContainer_light = Color(0xFFFBEBE4)
val md_surfaceContainerHigh_light = Color(0xFFF6E5DD)
val md_surfaceContainerHighest_light = Color(0xFFF0DFD8)

// ---- Dark ----
val md_primary_dark = Color(0xFFFFB59E)
val md_onPrimary_dark = Color(0xFF5C1900)
val md_primaryContainer_dark = Color(0xFF7B2D10)
val md_onPrimaryContainer_dark = Color(0xFFFFDBCF)
val md_secondary_dark = Color(0xFFE7BDB0)
val md_onSecondary_dark = Color(0xFF442A20)
val md_secondaryContainer_dark = Color(0xFF5D4035)
val md_onSecondaryContainer_dark = Color(0xFFFFDBCF)
val md_tertiary_dark = Color(0xFFD9C58D)
val md_onTertiary_dark = Color(0xFF3A2F05)
val md_tertiaryContainer_dark = Color(0xFF524619)
val md_onTertiaryContainer_dark = Color(0xFFF6E1A6)
val md_error_dark = Color(0xFFFFB4AB)
val md_onError_dark = Color(0xFF690005)
val md_errorContainer_dark = Color(0xFF93000A)
val md_onErrorContainer_dark = Color(0xFFFFDAD6)
val md_background_dark = Color(0xFF1A110D)
val md_onBackground_dark = Color(0xFFF1DFD8)
val md_surface_dark = Color(0xFF1A110D)
val md_onSurface_dark = Color(0xFFF1DFD8)
val md_surfaceVariant_dark = Color(0xFF53433E)
val md_onSurfaceVariant_dark = Color(0xFFD8C2BA)
val md_outline_dark = Color(0xFFA08D85)
val md_outlineVariant_dark = Color(0xFF53433E)
val md_inverseSurface_dark = Color(0xFFF1DFD8)
val md_inverseOnSurface_dark = Color(0xFF3A2F2B)
val md_inversePrimary_dark = Color(0xFFBB3E1C)
val md_scrim_dark = Color(0xFF000000)
val md_surfaceDim_dark = Color(0xFF1A110D)
val md_surfaceBright_dark = Color(0xFF423630)
val md_surfaceContainerLowest_dark = Color(0xFF140C09)
val md_surfaceContainerLow_dark = Color(0xFF231915)
val md_surfaceContainer_dark = Color(0xFF271C18)
val md_surfaceContainerHigh_dark = Color(0xFF322722)
val md_surfaceContainerHighest_dark = Color(0xFF3D312C)
