package com.template.core.designsystem.theme

import androidx.compose.ui.graphics.Color

/**
 * Ember — Material 3 color tokens (coral-seeded brand). Every on-/container pairing meets WCAG AA
 * (4.5:1 body, 3:1 large). Raw role values; schemes are assembled in [EmberTheme]. Source of truth:
 * docs/design/Ember*.dc.html. Components read `MaterialTheme.colorScheme`, never raw hex.
 */

// ---- Light ----
internal val primaryLight = Color(0xFFBB3E1C)
internal val onPrimaryLight = Color(0xFFFFFFFF)
internal val primaryContainerLight = Color(0xFFFFDBCF)
internal val onPrimaryContainerLight = Color(0xFF3A0B00)
internal val secondaryLight = Color(0xFF77574E)
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFFFFDBCF)
internal val onSecondaryContainerLight = Color(0xFF2C150D)
internal val tertiaryLight = Color(0xFF6C5D2F)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFFF6E1A6)
internal val onTertiaryContainerLight = Color(0xFF221B00)
internal val errorLight = Color(0xFFBA1A1A)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFFFDAD6)
internal val onErrorContainerLight = Color(0xFF410002)
internal val backgroundLight = Color(0xFFFFF8F6)
internal val onBackgroundLight = Color(0xFF231915)
internal val surfaceLight = Color(0xFFFFF8F6)
internal val onSurfaceLight = Color(0xFF231915)
internal val surfaceVariantLight = Color(0xFFF5DED6)
internal val onSurfaceVariantLight = Color(0xFF53433E)
internal val outlineLight = Color(0xFF85736C)
internal val outlineVariantLight = Color(0xFFD8C2BA)
internal val inverseSurfaceLight = Color(0xFF3A2F2B)
internal val inverseOnSurfaceLight = Color(0xFFFFEDE7)
internal val inversePrimaryLight = Color(0xFFFFB59E)
internal val scrimLight = Color(0xFF000000)
internal val surfaceDimLight = Color(0xFFE7D7CF)
internal val surfaceBrightLight = Color(0xFFFFF8F6)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowLight = Color(0xFFFFF1EC)
internal val surfaceContainerLight = Color(0xFFFBEBE4)
internal val surfaceContainerHighLight = Color(0xFFF6E5DD)
internal val surfaceContainerHighestLight = Color(0xFFF0DFD8)

// ---- Dark ----
internal val primaryDark = Color(0xFFFFB59E)
internal val onPrimaryDark = Color(0xFF5C1900)
internal val primaryContainerDark = Color(0xFF7B2D10)
internal val onPrimaryContainerDark = Color(0xFFFFDBCF)
internal val secondaryDark = Color(0xFFE7BDB0)
internal val onSecondaryDark = Color(0xFF442A20)
internal val secondaryContainerDark = Color(0xFF5D4035)
internal val onSecondaryContainerDark = Color(0xFFFFDBCF)
internal val tertiaryDark = Color(0xFFD9C58D)
internal val onTertiaryDark = Color(0xFF3A2F05)
internal val tertiaryContainerDark = Color(0xFF524619)
internal val onTertiaryContainerDark = Color(0xFFF6E1A6)
internal val errorDark = Color(0xFFFFB4AB)
internal val onErrorDark = Color(0xFF690005)
internal val errorContainerDark = Color(0xFF93000A)
internal val onErrorContainerDark = Color(0xFFFFDAD6)
internal val backgroundDark = Color(0xFF1A110D)
internal val onBackgroundDark = Color(0xFFF1DFD8)
internal val surfaceDark = Color(0xFF1A110D)
internal val onSurfaceDark = Color(0xFFF1DFD8)
internal val surfaceVariantDark = Color(0xFF53433E)
internal val onSurfaceVariantDark = Color(0xFFD8C2BA)
internal val outlineDark = Color(0xFFA08D85)
internal val outlineVariantDark = Color(0xFF53433E)
internal val inverseSurfaceDark = Color(0xFFF1DFD8)
internal val inverseOnSurfaceDark = Color(0xFF3A2F2B)
internal val inversePrimaryDark = Color(0xFFBB3E1C)
internal val scrimDark = Color(0xFF000000)
internal val surfaceDimDark = Color(0xFF1A110D)
internal val surfaceBrightDark = Color(0xFF423630)
internal val surfaceContainerLowestDark = Color(0xFF140C09)
internal val surfaceContainerLowDark = Color(0xFF231915)
internal val surfaceContainerDark = Color(0xFF271C18)
internal val surfaceContainerHighDark = Color(0xFF322722)
internal val surfaceContainerHighestDark = Color(0xFF3D312C)
